name: dscript_exec
description: Bash like command piping and redirecting for Dart to make writing Dart scripts easier.
version: 2.0.1
homepage: https://github.com/desktop-dart/dscript_exec
author: Ravi Teja Gudapti <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
